#!/bin/bash

set -e -u

cd $(dirname $0)

source "../scripts/tfhelpers.sh"

terraform init
terraform apply

greenpeace_terraform_email=$(tfoutput greenpeace_terraform_email)

gcloud iam service-accounts keys list \
  --iam-account $greenpeace_terraform_email \
  --managed-by user \
  --format json | jq -r .[].name | while read key _; do
  gcloud iam service-accounts keys delete $key \
    --iam-account $greenpeace_terraform_email \
    --quiet
done

gcloud iam service-accounts keys create \
  ../sensitive/greenpeace-terraform.json \
  --iam-account $greenpeace_terraform_email

gcloud secrets versions list concourse_bot_private_key \
  --format json \
  | jq -r '[.[] | select(.state == "ENABLED")] | first | .name' \
  | xargs gcloud secrets versions access \
  > ../sensitive/concourse_bot_private_key

jq -n '{ "greenpeace_gcp_credentials_json": $credentials[] | tojson,
         "greenpeace_private_key": $private_key }' \
  --slurpfile credentials ../sensitive/greenpeace-terraform.json \
  --arg private_key "$(cat ../sensitive/concourse_bot_private_key)" \
  > ../sensitive/vars.yml

# TODO: actually validate that these secrets are present with gcloud cli
echo
echo "ensure that the following secrets have been added to GCP Secret Manager:"
echo "- production-wavefront_token"
echo "- production-ci-github_client_id"
echo "- production-ci-github_client_secret"
echo "- dispatcher-concourse-github_client_id"
echo "- dispatcher_concourse-github_client_secret"

echo
echo "set the initial bootstrapping pipeline to a running concourse:"
echo 'ytt -v cluster=dispatcher -f pipeline/ | \'
echo '  fly -t dev set-pipeline \'
echo '    -l sensitive/vars.yml \'
echo '    -p dispatcher-greenpeace \'
echo '    -c -'
