#!/bin/bash

set -e -u

cd $(dirname $0)

terraform init

terraform apply

greenpeace_terraform_email=$(terraform output greenpeace_terraform_email)

gcloud iam service-accounts keys list \
  --iam-account $greenpeace_terraform_email \
  --managed-by user \
  --format json | jq -r .[].name | while read key _; do
  gcloud iam service-accounts keys delete $key \
    --iam-account $greenpeace_terraform_email \
    --quiet
done

gcloud iam service-accounts keys create \
  ../sensitive/greenpeace-terraform.json \
  --iam-account $greenpeace_terraform_email

jq -n '{ "gcp_credentials_json": $credentials[] | tojson }' \
  --slurpfile credentials ../sensitive/greenpeace-terraform.json \
  > ../sensitive/vars.yml

# TODO: actually validate that these secrets are present with gcloud cli
echo
echo "ensure that the following secrets have been added to GCP Secret Manager:"
echo "- production-ci-github_client_id"
echo "- production-ci-github_client_secret"