platform: linux

image_resource:
  type: registry-image
  source: { repository: google/cloud-sdk }

inputs:
  - name: greenpeace
  - name: terraform
  - name: root-token-enc
  - name: vault-backend-migrator

outputs:
  - name: secrets

params:
  GCP_CREDENTIALS_JSON:
  TERRAFORM_VERSION:
  USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

run:
  path: greenpeace/tasks/scripts/export-secrets.sh
  user: root
