platform: linux

image_resource:
  type: registry-image
  source: { repository: google/cloud-sdk }

inputs:
  - name: greenpeace
  - name: terraform
  - name: secrets
  - name: vault-backend-migrator

params:
  GCP_CREDENTIALS_JSON:
  CLUSTER_NAME:
  TERRAFORM_VERSION:
  USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

run:
  path: greenpeace/tasks/scripts/initialize-vault.sh
  user: root
