platform: linux

image_resource:
  type: registry-image
  source:
    repository: k14s/image
    tag: kbld-rand-1592942790507001000-1148625018150

inputs:
- name: greenpeace

outputs:
- name: rendered

params:
  ARGS:

run:
  path: bash
  args:
  - -c
  - ytt $ARGS > rendered/pipeline.yml
  user: root
