platform: linux

image_resource:
  type: registry-image
  source: {repository: alpine/git}

inputs:
- name: input

outputs:
- name: output

params:
  FILE:
  CONTENT:
  COMMIT:

run:
  path: sh
  args:
  - -c
  - |
    cd input
    printf "$CONTENT" > "$FILE"
    git add -A

    git config --global user.email "ci@localhost"
    git config --global user.name "CI Bot"

    git commit -m "$COMMIT" --allow-empty
