#!/bin/bash

set -e -u

if [ "$#" != "1" ]; then
  echo "usage: $0 <ci|hush-house|...>" >&2
  exit 1
fi

# TODO: not hard-coded to production
cd $(dirname $0)/../terraform/production

database="$1"
output="$(terraform output -json)"

function read_attr() {
  local attr="$1"
  jq -r '.["'$database'_database_'$attr'"].value' <<< $output
}

ip="$(read_attr ip)"
password="$(read_attr password)"

ca_cert=/tmp/${database}-ca.crt
read_attr ca_cert > $ca_cert

client_cert=/tmp/${database}-client.crt
read_attr cert > $client_cert

client_key=/tmp/${database}-client.key
read_attr private_key > $client_key
chmod 0600 $client_key

echo "ip:       ${ip}"
echo "password: ${password}"
echo
echo "ca cert:     ${ca_cert}"
echo "client cert: ${client_cert}"
echo "client key:  ${client_key}"
echo
echo "connect with...:"
echo '  psql "'"host=${ip} user=atc sslcert=${client_cert} sslkey=${client_key} sslrootcert=${ca_cert} sslmode=verify-ca"'"'
