#!/bin/bash

set -euo pipefail

dir="$(dirname $0)"
source "$dir/tfhelpers.sh"


if [ "$#" != "1" ]; then
  echo "usage: $0 production|dispatcher|...>" >&2
  exit 1
fi

env="$1"
cd "$(dirname $0)/../terraform/environments/$env"

terraform init
terraform workspace select "$env"

echo "switching kube context to cluster $(tfoutput cluster_name)..."
gcloud container clusters get-credentials "$(tfoutput cluster_name)" --zone "$(tfoutput cluster_zone)" --project "$(tfoutput project)"

kubectl -n "$(tfoutput vault_namespace)" exec -it vault-0 -- sh
