#!/bin/bash

set -euo pipefail

path="$(realpath $0)"
dir="$(dirname $path)"

fail () {
    echo $@ 1>&2
    exit 1
}

[[ $# -lt 3 ]] && fail "usage: $0 env secret_name secret_value (or k1=v1 k2=v2)"

env="$1"
shift

EDITOR="python $dir/patch.py $@" "$dir/edit-secrets" "$env"
